- name: Build Princess Bot image on VPS
  docker_image:
    name: princess_bot_image
    state: present
    force_source: yes
    source: build
    build:
      path: "{{VPS_APP_PATH}}"
      dockerfile: "./.docker/{{NODE_ENV}}.dockerfile"

- name: Restart Princess Bot container on VPS
  docker_container:
    name: princess_bot
    image: princess_bot_image
    restart: yes
    recreate: yes
    network_mode: "host"
    env:
      NODE_ENV: "{{NODE_ENV}}"
      RELEASE: "{{RELEASE}}"
      BOT_TOKEN: "{{BOT_TOKEN}}"
      MONGODB_URI: "{{MONGODB_URI}}"
      ADMIN_ID: "{{ADMIN_ID}}"
      AUTHOR_TWITTER_LINK: "{{AUTHOR_TWITTER_LINK}}"
      GITHUB_REPO_URL: "{{GITHUB_REPO_URL}}"
      WISHLIST_TG_URL: "{{WISHLIST_TG_URL}}"
      WISHLIST_GITHUB_REPO_URL: "{{WISHLIST_GITHUB_REPO_URL}}"
      CHATGPT_TG_URL: "{{CHATGPT_TG_URL}}"
      CHATGPT_GITHUB_REPO_URL: "{{CHATGPT_GITHUB_REPO_URL}}"
